replicaCount: 1

image: 
  repository: "us.gcr.io/oc-devops-dev/odysseycloud-io"
  tag: "10ab4a1a9b981d1dabca8720316534cbf5813d7a"
  pullPolicy: Always

  publicUrl: "odysseycloud.io"

nameOverride: ''
fullnameOverride: ''

service:
  annotation: {}
  type: NodePort
  port: 80

resources: 
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi


nodeSelector: {}

tolerations: []

antiAffinity:
  enabled: true


app:
  initialDelaySeconds: 10
  periodSeconds: 10
  successsThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 5

  