replicaCount: 1

image: 
  repository: "bradmccoydev/terraform-plan-validator"
  tag: "b249f4e6d2de2dc6623825fdbcedbbf3bbf4c1ab"
  pullPolicy: Always

  publicUrl: "bradmccoy.io"

nameOverride: ''
fullnameOverride: ''

service:
  annotation: {}
  type: NodePort
  port: 80


ingress-aws: 
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: bradmccoy.io
    cert-manager.io/cluster-issuer: letsencrypt-aws-certs
    nginx.ingress.kubernetes.io/configuration-snippet:
      more_clear_headers Server X-Powered-By;
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  pathType: Prefix
  hosts:
  - tf.bradmccoy.io
  tls:
  - hosts:
      - tf.bradmccoy.io
    secretName: letsencrypt-bradmccoy-io


resources: 
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

# config:
#   appReferral:
#     enabled: true
#   monitoring:
#     enabled: true

#   media:
#     url: ''

#   monitoring: 
#     enabled: false
  


nodeSelector: {}

tolerations: []

antiAffinity:
  enabled: true


app:
  initialDelaySeconds: 10
  periodSeconds: 10
  successsThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 5

  