apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terraform-plan-validator.fullname" . }}
  labels:
    app: {{ include "terraform-plan-validator.name" . }}
    chart: {{ include "terraform-plan-validator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec: 
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels: 
      app: {{ include "terraform-plan-validator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "terraform-plan-validator.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.antiAffinity.enabled }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: 
          - labelSelector: 
              matchExpressions:
              - key: app
                operator: In
                values: 
                - {{ include "oc-web.name" . }}
              - key: release
                operator: In
                values: 
                - {{ .Release.Name }}
            topologyKey: "kubernetes.io/hostname"
      {{- end }}
      containers: 
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports: 
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: PORT
          value: "{{ .Values.port }}"
        - name: PROM_TRACING
          value: "{{ .Values.promTracing }}"   
        - name: PUBLIC_URL
          value: "{{ .Values.publicUrl }}"                      
        resources:
{{ toYaml .Values.resources | indent 12 }}
  {{- with .Values.nodeSelector }}          
    nodeSelector: 
{{ toYaml . | indent 8 }}      
  {{- end }}
  {{- with .Values.tolerations }}
    tolerations:
{{ toYaml . | indent 8 }}      
  {{- end }}