name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        OPA_AZURE_POLICY: ./../../opa-azure-policy.rego  
    
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bradmccoydev/terraform-plan-validator:${{ github.sha }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'bradmccoydev/terraform-plan-validator:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
      
    - name: Docker Push
      run: docker push bradmccoydev/terraform-plan-validator:${{ github.sha }}

    - name: update tag for oc-web image on deployment
      run: |-
        export $GITHUB_SHA
        find "chart" -name "*.tmpl" -exec bash -c 'envsubst < $1 > chart/${{ env.CLIENT_ENVIRONMENT }}-values.yaml' _ {} \;
        ls chart/
        cat chart/${{ env.CLIENT_ENVIRONMENT }}-values.yaml
        git status   
        git config --global user.email "github_actions@odysseycloud.io"
        git config --global user.name "github_actions"
        git add chart/${{ env.CLIENT_ENVIRONMENT }}-values.yaml
        echo $IMAGE_TAG
        git commit -m "update image tag with  $GITHUB_SHA"
        git push
